language: julia
dist: trusty
sudo: false
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
addons:
  apt:
    packages:
      - libnlopt0
after_success:
  - julia -e 'cd(Pkg.dir("TimeModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
